FROM python:3.9

WORKDIR /usr/kanban
RUN mkdir -p data

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
COPY .flaskenv-uat .flaskenv


EXPOSE 5000
CMD [ "flask", "run", "--host=0.0.0.0" ]